### ISSUE TITLE
Ссылка на демо

### ISSUE THREAD

**Issue by VadimCpp** [Svetlana-K-design/hmarket-test#1]
Прошу опбликовать проект на ghpages

**Comment by Svetlana-K-design** [comment]
https://svetlana-k-design.github.io/hmarket-test/

**Comment by VadimCpp** [comment]
Спасибо, добавьте пожалуйста ссылку в описание проекта

**Comment by Svetlana-K-design** [comment]
Добавила в описание (About). Или нужно сделать readMe файл?

**Comment by VadimCpp** [comment]
Рядом с полем "Description" есть ссылка "Website". Поместите ссылку в поле "Website", пожалуйста.

**Comment by Svetlana-K-design** [comment]
Да, написала

**Comment by VadimCpp** [comment]
Спасибо, закрыл
